language: ruby
rvm:
- 2.1.5
services: postgres
before_script:
- rm config/database.yml
- cp config/database.travis.yml config/database.yml
- psql -c 'create database maslow_test;' -U postgres
- bundle exec rake db:migrate
addons:
  postgresql: '9.3'
deploy:
  provider: heroku
  api_key:
    secure: jGhIw9ZHrmpwIEYzuQazgEN2cW2xjLEc5Dh8eBEIW8rRZqGYBOPkpEhF6XfZUy/lSkZC6EsYJX9Vu39m8FiSWGPYnn2KoPXcQETXsru8FAesUTcpXr8HfqtL5ecY7mgmgDEdKCGEhXbD+IXKzwPnrtbgRhnVSCrKCAFCZBysYc0=
  app: gds-civil-service-maslow
  run: "rake db:migrate"
